// 电影数据 - 直接内嵌在HTML中
const movieData = {
    // 统计数据
    stats: {
        total: 100,
        avgRating: 8.93,  // 我帮你计算了平均评分
        yearRange: "1939-2025",
        completeness: "100%"
    },
    
    // 完整电影列表（你的真实数据）
    movies: [
        { rank: 1, name: '我不是药神', rating: 9.6, actors: '徐峥,王传君,周一围', year: 2018, region: '' },
        { rank: 2, name: '肖申克的救赎', rating: 9.5, actors: '蒂姆·罗宾斯,摩根·弗里曼,鲍勃·冈顿', year: 1994, region: '加拿大' },
        { rank: 3, name: '海上钢琴师', rating: 9.3, actors: '蒂姆·罗斯,比尔·努恩 ,克兰伦斯·威廉姆斯三世', year: 2019, region: '' },
        { rank: 4, name: '绿皮书', rating: 9.5, actors: '维果·莫腾森,马赫沙拉·阿里,琳达·卡德里尼', year: 2019, region: '' },
        { rank: 5, name: '霸王别姬', rating: 9.4, actors: '张国荣,张丰毅,巩俐', year: 1993, region: '' },
        { rank: 6, name: '美丽人生', rating: 9.3, actors: '罗伯托·贝尼尼,朱斯蒂诺·杜拉诺,赛尔乔·比尼·布斯特里克', year: 2020, region: '' },
        { rank: 7, name: '这个杀手不太冷', rating: 9.6, actors: '让·雷诺,娜塔莉·波特曼,加里·奥德曼', year: 2024, region: '' },
        { rank: 8, name: '星际穿越', rating: 9.3, actors: '马修·麦康纳,安妮·海瑟薇,杰西卡·查斯坦', year: 2014, region: '' },
        { rank: 9, name: '盗梦空间', rating: 9.0, actors: '莱昂纳多·迪卡普里奥,渡边谦,约瑟夫·高登-莱维特', year: 2010, region: '' },
        { rank: 10, name: '泰坦尼克号', rating: 9.6, actors: '莱昂纳多·迪卡普里奥,凯特·温丝莱特,比利·赞恩', year: 1998, region: '' },
        { rank: 11, name: '怦然心动', rating: 8.9, actors: '玛德琳·卡罗尔,卡兰·麦克奥利菲,艾丹·奎因', year: 2010, region: '美国' },
        { rank: 12, name: '小偷家族', rating: 8.1, actors: '中川雅也,安藤樱,松冈茉优', year: 2018, region: '' },
        { rank: 13, name: '阿甘正传', rating: 9.4, actors: '汤姆·汉克斯,罗宾·怀特,加里·西尼斯', year: 1994, region: '美国' },
        { rank: 14, name: '楚门的世界', rating: 8.9, actors: '金·凯瑞,劳拉·琳妮,诺亚·艾默里奇', year: 1998, region: '罗马尼亚' },
        { rank: 15, name: '千与千寻', rating: 9.3, actors: '柊瑠美,周冬雨,井柏然', year: 2019, region: '' },
        { rank: 16, name: '寻梦环游记', rating: 9.6, actors: '安东尼·冈萨雷斯,本杰明·布拉特,盖尔·加西亚·贝纳尔', year: 2017, region: '' },
        { rank: 17, name: '哪吒之魔童降世', rating: 9.6, actors: '吕艳婷,囧森瑟夫,瀚墨', year: 2019, region: '' },
        { rank: 18, name: '情书', rating: 8.9, actors: '中山美穗,丰川悦司,酒井美纪', year: 1999, region: '' },
        { rank: 19, name: '触不可及', rating: 9.1, actors: '弗朗索瓦·克鲁塞,奥马·希,安娜·勒尼', year: 2011, region: '法国' },
        { rank: 20, name: '辛德勒的名单', rating: 9.2, actors: '连姆·尼森,拉尔夫·费因斯,本·金斯利', year: 1993, region: '美国' },
        { rank: 21, name: '少年派的奇幻漂流', rating: 9.0, actors: '苏拉·沙玛,伊尔凡·可汗,塔布', year: 2012, region: '' },
        { rank: 22, name: '何以为家', rating: 9.3, actors: '赞恩·阿尔·拉菲亚,约丹诺斯·希费罗,博鲁瓦蒂夫·特雷杰·班科尔', year: 2019, region: '' },
        { rank: 23, name: '放牛班的春天', rating: 9.5, actors: '热拉尔·朱诺,弗朗西斯·贝尔兰德,凯德·麦拉德', year: 2004, region: '' },
        { rank: 24, name: '摔跤吧！爸爸', rating: 9.8, actors: '阿米尔·汗,沙克希·坦沃,法缇玛·萨那·纱卡', year: 2017, region: '' },
        { rank: 25, name: '忠犬八公的故事', rating: 9.3, actors: 'Forest,理查·基尔,琼·艾伦', year: 2009, region: '美国' },
        { rank: 26, name: '死亡诗社', rating: 8.7, actors: '罗宾·威廉姆斯,伊桑·霍克,罗伯特·肖恩·莱纳德', year: 1989, region: '加拿大' },
        { rank: 27, name: '小丑', rating: 8.6, actors: '杰昆·菲尼克斯,罗伯特·德尼罗,亚历克·鲍德温', year: 2019, region: '美国' },
        { rank: 28, name: '当幸福来敲门', rating: 9.3, actors: '威尔·史密斯,贾登·史密斯,坦迪·牛顿', year: 2008, region: '' },
        { rank: 29, name: '三傻大闹宝莱坞', rating: 9.1, actors: '阿米尔·汗,卡琳娜·卡普,马德哈万', year: 2011, region: '' },
        { rank: 30, name: '看不见的客人', rating: 9.4, actors: '马里奥·卡萨斯,阿娜·瓦格纳,何塞·科罗纳多', year: 2017, region: '' },
        { rank: 31, name: '活着', rating: 9.0, actors: '葛优,巩俐,牛犇', year: 1994, region: '法国' },
        { rank: 32, name: '你的名字。', rating: 9.3, actors: '上白石萌音,佟心竹,神木隆之介', year: 2016, region: '' },
        { rank: 33, name: '教父', rating: 9.3, actors: '马龙·白兰度,阿尔·帕西诺,詹姆斯·凯恩', year: 1972, region: '美国' },
        { rank: 34, name: '熔炉', rating: 8.8, actors: '孔刘,郑裕美,金智英', year: 2011, region: '韩国' },
        { rank: 35, name: '天堂电影院', rating: 9.3, actors: '菲利浦·诺瓦雷,雅克·贝汉,马克·莱昂纳蒂', year: 2021, region: '' },
        { rank: 36, name: '疯狂动物城', rating: 9.5, actors: '金妮弗·古德温,杰森·贝特曼,伊德瑞斯·艾尔巴', year: 2016, region: '' },
        { rank: 37, name: '龙猫', rating: 9.2, actors: '秦岚,糸井重里,岛本须美', year: 2018, region: '' },
        { rank: 38, name: '头号玩家', rating: 9.0, actors: '泰伊·谢里丹,奥利维亚·库克,本·门德尔松', year: 2018, region: '' },
        { rank: 39, name: '闻香识女人', rating: 8.8, actors: '阿尔·帕西诺,克里斯·奥唐纳,加布里埃尔·安瓦尔', year: 1992, region: '美国' },
        { rank: 40, name: '被嫌弃的松子的一生', rating: 8.5, actors: '中谷美纪,永山瑛太,伊势谷友介', year: 2006, region: '日本' },
        { rank: 41, name: '一一', rating: 8.9, actors: '吴文钦,金燕玲,李凯莉', year: 2017, region: '中国大陆' },
        { rank: 42, name: '末代皇帝', rating: 8.8, actors: '尊龙,彼得·奥图尔,陈冲', year: 1987, region: '日本' },
        { rank: 43, name: '超脱', rating: 8.7, actors: '阿德里安·布劳迪,马西娅·盖伊·哈登,詹姆斯·凯恩', year: 2011, region: '美国' },
        { rank: 44, name: '心灵奇旅', rating: 9.2, actors: '杰米·福克斯,蒂娜·菲,菲利西亚·拉斯海德', year: 2020, region: '' },
        { rank: 45, name: '海蒂和爷爷', rating: 9.5, actors: '阿努克·斯特芬 ,布鲁诺·冈茨,昆林·艾格匹', year: 2019, region: '' },
        { rank: 46, name: '机器人总动员', rating: 9.3, actors: '本·贝尔特,艾丽莎·奈特,杰夫·格尔林', year: 2008, region: '美国' },
        { rank: 47, name: '西西里的美丽传说', rating: 8.2, actors: '莫妮卡·贝鲁奇,朱塞佩·苏尔法罗,玛蒂尔德·皮亚纳', year: 2000, region: '意大利' },
        { rank: 48, name: '三块广告牌', rating: 8.6, actors: '弗兰西斯·麦克多蒙德,伍迪·哈里森,山姆·洛克威尔', year: 2018, region: '' },
        { rank: 49, name: '海边的曼彻斯特', rating: 8.8, actors: '卡西·阿弗莱克,卢卡斯·赫奇斯,米歇尔·威廉姆斯', year: 2017, region: '' },
        { rank: 50, name: '本杰明·巴顿奇事', rating: 8.8, actors: '布拉德·皮特,凯特·布兰切特,塔拉吉·P·汉森', year: 2008, region: '美国' },
        { rank: 51, name: '布达佩斯大饭店', rating: 8.7, actors: '拉尔夫·费因斯,托尼·雷沃罗利,西尔莎·罗南', year: 2014, region: '德国' },
        { rank: 52, name: '让子弹飞', rating: 8.5, actors: '姜文,周润发,葛优', year: 2010, region: '' },
        { rank: 53, name: '哪吒之魔童闹海', rating: 9.8, actors: '吕艳婷,瀚墨,囧森瑟夫', year: 2025, region: '' },
        { rank: 54, name: '乱世佳人', rating: 9.1, actors: '费雯·丽,克拉克·盖博,奥利维娅·德哈维兰', year: 1939, region: '美国' },
        { rank: 55, name: '美国往事', rating: 9.1, actors: '罗伯特·德尼罗,詹姆斯·伍兹,伊丽莎白·麦戈文', year: 2015, region: '' },
        { rank: 56, name: '美丽心灵', rating: 8.8, actors: '罗素·克劳,詹妮弗·康纳利,艾德·哈里斯', year: 2001, region: '美国' },
        { rank: 57, name: '爱在黎明破晓前', rating: 8.7, actors: '伊桑·霍克,朱莉·德尔佩,安德莉亚·埃克特', year: 1995, region: '美国' },
        { rank: 58, name: '搏击俱乐部', rating: 8.7, actors: '爱德华·哈里森·诺顿,布拉德·皮特,海伦娜·伯翰·卡特', year: 1999, region: '意大利' },
        { rank: 59, name: '消失的爱人', rating: 8.7, actors: '本·阿弗莱克,裴淳华,尼尔·帕特里克·哈里斯', year: 2014, region: '美国' },
        { rank: 60, name: '低俗小说', rating: 8.7, actors: '约翰·特拉沃尔塔,阿曼达·普拉莫,乌玛·瑟曼', year: 1994, region: '法国' },
        { rank: 61, name: '阿凡达', rating: 9.4, actors: '萨姆·沃辛顿,佐伊·索尔达娜,米歇尔·罗德里格兹', year: 2010, region: '' },
        { rank: 62, name: '飞屋环游记', rating: 8.9, actors: '爱德华·阿斯纳,克里斯托弗·普卢默,乔丹·长井', year: 2009, region: '' },
        { rank: 63, name: '无间道', rating: 9.1, actors: '刘德华,梁朝伟,黄秋生', year: 2003, region: '' },
        { rank: 64, name: '蝴蝶效应', rating: 8.7, actors: '约翰·帕特里克·阿梅多利,罗根·勒曼,卡梅隆·布莱特', year: 2004, region: '美国' },
        { rank: 65, name: '窃听风暴', rating: 9.0, actors: '乌尔里希·穆埃,塞巴斯蒂安·科赫,马蒂娜·格德克', year: 2006, region: '德国' },
        { rank: 66, name: '时空恋旅人', rating: 8.9, actors: '瑞秋·麦克亚当斯,多姆纳尔·格里森,比尔·奈伊', year: 2013, region: '英国' },
        { rank: 67, name: '哈尔的移动城堡', rating: 9.5, actors: '木村拓哉,于适,倍赏千惠子', year: 2024, region: '' },
        { rank: 68, name: '飞越疯人院', rating: 8.7, actors: '杰克·尼科尔森,路易丝·弗莱彻,威廉·雷德菲尔德', year: 1975, region: '美国' },
        { rank: 69, name: '大话西游之大圣娶亲', rating: 8.8, actors: '周星驰,朱茵,莫文蔚', year: 2014, region: '' },
        { rank: 70, name: '天空之城', rating: 9.4, actors: '田中真弓,横泽启子,初井言荣', year: 2023, region: '' },
        { rank: 71, name: '花束般的恋爱', rating: 8.9, actors: '有村架纯,菅田将晖,细田佳央太', year: 2022, region: '' },
        { rank: 72, name: '心灵捕手', rating: 8.4, actors: '罗宾·威廉姆斯,马特·达蒙,明妮·德里弗', year: 1997, region: '美国' },
        { rank: 73, name: '爱在日落黄昏时', rating: 8.7, actors: '伊桑·霍克,朱莉·德尔佩,弗农·多布切夫', year: 2015, region: '' },
        { rank: 74, name: '天使爱美丽', rating: 8.4, actors: '奥黛丽·塔图,马修·卡索维茨,吕菲斯', year: 2001, region: '比利时' },
        { rank: 75, name: '复仇者联盟4：终局之战', rating: 9.1, actors: '小罗伯特·唐尼,克里斯·埃文斯,马克·鲁法洛', year: 2019, region: '' },
        { rank: 76, name: '七宗罪', rating: 8.7, actors: '布拉德·皮特,摩根·弗里曼,凯文·史派西', year: 1995, region: '美国' },
        { rank: 77, name: '春光乍泄', rating: 9.2, actors: '张国荣,梁朝伟,张震', year: 1997, region: '中国大陆' },
        { rank: 78, name: '重庆森林', rating: 8.6, actors: '梁朝伟,王菲,金城武', year: 1994, region: '中国大陆' },
        { rank: 79, name: '猫鼠游戏', rating: 8.6, actors: '莱昂纳多·迪卡普里科,汤姆·汉克斯,克里斯托弗·沃肯', year: 2003, region: '' },
        { rank: 80, name: '罗马假日', rating: 9.0, actors: '格利高里·派克,奥黛丽·赫本,埃迪·艾伯特', year: 1953, region: '意大利' },
        { rank: 81, name: '穿条纹睡衣的男孩', rating: 9.0, actors: '阿沙·巴特菲尔德,维拉·法梅加,大卫·休里斯', year: 2008, region: '英国' },
        { rank: 82, name: '釜山行', rating: 8.9, actors: '孔刘,郑裕美,马东锡', year: 2016, region: '法国' },
        { rank: 83, name: '菊次郎的夏天', rating: 8.8, actors: '北野武,关口雄介,岸本 加世子', year: 2020, region: '' },
        { rank: 84, name: '钢琴家', rating: 8.9, actors: '阿德里安·布劳迪,艾米莉娅·福克斯,米乔·赞布罗斯基', year: 2002, region: '法国' },
        { rank: 85, name: '好东西', rating: 9.2, actors: '宋佳,钟楚曦,曾慕梅', year: 2024, region: '' },
        { rank: 86, name: '辩护人', rating: 8.8, actors: '宋康昊,吴达洙,郭度沅', year: 2013, region: '韩国' },
        { rank: 87, name: '饮食男女', rating: 8.8, actors: '郎雄,吴倩莲,杨贵媚', year: 1994, region: '美国' },
        { rank: 88, name: '剪刀手爱德华', rating: 8.8, actors: '约翰尼·德普,薇诺娜·瑞德,黛安娜·维斯特', year: 1990, region: '美国' },
        { rank: 89, name: '十二怒汉', rating: 9.1, actors: '亨利·方达,李·科布,马丁·鲍尔萨姆', year: 1957, region: '美国' },
        { rank: 90, name: '入殓师', rating: 8.6, actors: '本木雅弘,广末凉子,山崎努', year: 2021, region: '' },
        { rank: 91, name: '蝙蝠侠：黑暗骑士', rating: 9.3, actors: '克里斯蒂安·贝尔,希斯·莱杰,阿伦·伊克哈特', year: 2008, region: '阿根廷' },
        { rank: 92, name: '素媛', rating: 9.1, actors: '李来,薛景求,严智苑', year: 2013, region: '韩国' },
        { rank: 93, name: '傲慢与偏见', rating: 8.4, actors: '马修·麦克费登,吉娜·马隆,妲露拉·莱莉', year: 2008, region: '' },
        { rank: 94, name: '两杆大烟枪', rating: 8.7, actors: '杰森·弗莱明,德克斯特·弗莱彻,杰森·斯坦森', year: 1998, region: '英国' },
        { rank: 95, name: '奥本海默', rating: 9.3, actors: '基里安·墨菲,艾米莉·布朗特,马特·达蒙', year: 2023, region: '' },
        { rank: 96, name: '大鱼', rating: 8.6, actors: '伊万·麦克格雷格,阿尔伯特·芬尼,杰西卡·兰格', year: 2003, region: '美国' },
        { rank: 97, name: '禁闭岛', rating: 8.7, actors: '莱昂纳多·迪卡普里奥,马克·鲁法洛,本·金斯利', year: 2010, region: '德国' },
        { rank: 98, name: '致命魔术', rating: 8.8, actors: '休·杰克曼,克里斯蒂安·贝尔,迈克尔·凯恩', year: 2006, region: '意大利' },
        { rank: 99, name: '真爱至上', rating: 8.6, actors: '休·格兰特,比尔·奈伊,连姆·尼森', year: 2003, region: '英国' },
        { rank: 100, name: '模仿游戏', rating: 9.3, actors: '本尼迪克特·康伯巴奇,凯拉·奈特莉,马修·古迪', year: 2015, region: '' }
    ]
};